### PR TITLE
Convert to use middleware

### PR DESCRIPTION
**Pull request by rynowak**
Prototype of using middleware for Swagger document / Swagger UI

### CODE REVIEW

**Comment by domaindrivendev** [comment]
I have a similar implementation (not yet pushed) but am using a custom IRouter instead of middleware. The advantage being that the routing middleware does the template parsing for me.

I think you had originally suggested an IRouter implementation, is there any reason why middleware would be a better approach?

**Comment by rynowak** [comment]
It really ends up being a wash :laughing: 

Would you care about using routing to generate links?

**Comment by domaindrivendev** [comment]
Here's the IRouter commit

https://github.com/domaindrivendev/Ahoy/commit/bb44ec5bee2429dd95ce3bb49e42915af91c3a92

**Comment by rynowak** [comment]
Yeah, it ends up being a bit of a wash really. I think either would work fine.
- With routing you don't have to do a manual call to match the URL
- With middleware you get to use DI so you don't need manual GetServices

The way the routing is set up (separate instance of RouterMiddleware) you wouldn't be able to use MVC to generate a link to swashbuckle (because it's in a separate route table). Not sure if there's ever been any demand for that.

**Pull request closed without merging**
